export const GET_FOLLOWERS_REQUEST = 'GET_FOLLOWERS_REQUEST';
export const GET_FOLLOWERS_RESPONSE = 'GET_FOLLOWERS_RESPONSE';
export const UPDATE_FOLLOWERS_REQUEST = 'UPDATE_FOLLOWERS_REQUEST';
export const UPDATE_FOLLOWERS_RESPONSE = 'UPDATE_FOLLOWERS_RESPONSE';

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_RESPONSE = 'GET_PROFILE_RESPONSE';
export const UPDATE_PROFILE_PHOTOS_REQUEST = 'UPDATE_PROFILE_PHOTOS_REQUEST';
export const UPDATE_PROFILE_PHOTOS_RESPONSE = 'UPDATE_PROFILE_PHOTOS_RESPONSE';

export const GET_PROFILE_PHOTOS_REQUEST = 'GET_PROFILE_PHOTOS_REQUEST';
export const GET_PROFILE_PHOTOS_RESPONSE = 'GET_PROFILE_PHOTOS_RESPONSE';

export const SEARCH_BY_TAG_REQUEST = 'SEARCH_BY_TAG_REQUEST';
export const SEARCH_BY_TAG_RESPONSE = 'SEARCH_BY_TAG_RESPONSE';

export const GET_POPULAR_REQUEST = 'GET_POPULAR_REQUEST';
export const GET_POPULAR_RESPONSE = 'GET_POPULAR_RESPONSE';

export const SEARCH_BY_USER_REQUEST = 'SEARCH_BY_USER_REQUEST';
export const SEARCH_BY_USER_RESPONSE = 'SEARCH_BY_USER_RESPONSE';

export const GET_TIMELINE_REQUEST = 'GET_TIMELINE_REQUEST';
export const GET_TIMELINE_RESPONSE = 'GET_TIMELINE_RESPONSE';
export const UPDATE_TIMELINE_RESPONSE = 'UPDATE_TIMELINE_RESPONSE';
